version: "3"
services:
  web:
    container_name: todo_list
    build: .
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      FLASK_RUN_HOST: 0.0.0.0
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"

  db:
    container_name: sqlite_db
    image: alpine:latest
    stdin_open: true
    volumes:
      - ./database:/data
    environment:
      - SQLITE_DATABASE=/data/todo.db

volumes:
  database: